on:
    pull_request: null
    push:
        branches:
            - 1.x

name: phpunit

jobs:
    phpunit:
        uses: spiral/gh-actions/.github/workflows/phpunit.yml@master
        with:
            os: >-
                ['ubuntu-latest']
            stability: >-
                ['prefer-lowest', 'prefer-stable']
